name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'Dockerfile'
      - 'app.py'
      - 'auth.py'
      - 'config.py'
      - 'schemas.py'
      - 'error_handlers.py'
      - 'utils.py'
      - 'routes/**'
      - 'storage/**'
      - 'requirements.txt'
      - '.github/workflows/ci-cd.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'app.py'
      - 'auth.py'
      - 'config.py'
      - 'schemas.py'
      - 'error_handlers.py'
      - 'utils.py'
      - 'routes/**'
      - 'storage/**'
      - 'requirements.txt'
      - '.github/workflows/ci-cd.yml'

env:
  REGISTRY: cerit.io
  IMAGE_NAME: molstar/mol-view-stories

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt

    - name: Run tests (if you have them)
      run: |
        # Add your test commands here
        echo "Running tests..."
        # python -m pytest tests/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Company Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.CERIT_REGISTRY_USERNAME }}
        password: ${{ secrets.CERIT_REGISTRY_PASSWORD }}

    - name: Test Docker login manually
      if: github.event_name != 'pull_request'
      run: |
        echo "=== Testing Docker login manually ==="
        echo "Testing docker login to ${{ env.REGISTRY }}"
        
        # Test if we can login with docker
        if docker login ${{ env.REGISTRY }} -u "${{ secrets.CERIT_REGISTRY_USERNAME }}" -p "${{ secrets.CERIT_REGISTRY_PASSWORD }}" 2>&1 | grep -q "Login Succeeded"; then
          echo "✓ Docker login successful"
          
          # Test if we can pull a simple image (if any exist)
          echo "Testing if we can access registry with docker..."
          docker pull ${{ env.REGISTRY }}/hello-world:latest 2>/dev/null || echo "No hello-world image found (this is OK)"
          
        else
          echo "✗ Docker login failed"
          echo "This indicates a credentials or registry configuration issue"
          exit 1
        fi

    - name: Debug registry access
      if: github.event_name != 'pull_request'
      run: |
        echo "Testing registry access..."
        echo "Registry: ${{ env.REGISTRY }}"
        echo "Image name: ${{ env.IMAGE_NAME }}"
        
        # Test 1: Basic registry root access (should work with valid credentials)
        echo "=== Test 1: Registry root access ==="
        ROOT_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -u "${{ secrets.CERIT_REGISTRY_USERNAME }}:${{ secrets.CERIT_REGISTRY_PASSWORD }}" \
          "https://${{ env.REGISTRY }}/v2/")
        echo "Root response code: $ROOT_RESPONSE"
        
        if [ "$ROOT_RESPONSE" = "200" ]; then
          echo "✓ Registry root access successful"
        else
          echo "✗ Registry root access failed - credentials may be invalid"
        fi
        
        # Test 2: Catalog access (requires specific permissions)
        echo "=== Test 2: Catalog access ==="
        CATALOG_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -u "${{ secrets.CERIT_REGISTRY_USERNAME }}:${{ secrets.CERIT_REGISTRY_PASSWORD }}" \
          "https://${{ env.REGISTRY }}/v2/_catalog")
        echo "Catalog response code: $CATALOG_RESPONSE"
        
        if [ "$CATALOG_RESPONSE" = "200" ]; then
          echo "✓ Catalog access successful"
        elif [ "$CATALOG_RESPONSE" = "401" ]; then
          echo "✗ Catalog access failed - user may not have catalog permissions"
        else
          echo "? Catalog access returned unexpected code: $CATALOG_RESPONSE"
        fi
        
        # Test 3: Try to access a specific repository (molstar project)
        echo "=== Test 3: Molstar project access ==="
        MOLSTAR_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -u "${{ secrets.CERIT_REGISTRY_USERNAME }}:${{ secrets.CERIT_REGISTRY_PASSWORD }}" \
          "https://${{ env.REGISTRY }}/v2/molstar/tags/list")
        echo "Molstar project response code: $MOLSTAR_RESPONSE"
        
        if [ "$MOLSTAR_RESPONSE" = "200" ]; then
          echo "✓ Molstar project exists and is accessible"
        elif [ "$MOLSTAR_RESPONSE" = "404" ]; then
          echo "? Molstar project doesn't exist yet (this is OK)"
        elif [ "$MOLSTAR_RESPONSE" = "401" ]; then
          echo "✗ Molstar project access denied - user may not have project permissions"
        else
          echo "? Molstar project access returned unexpected code: $MOLSTAR_RESPONSE"
        fi
        
        # Test 4: Check if user can create projects (try to push a minimal manifest)
        echo "=== Test 4: Project creation test ==="
        if [ "$ROOT_RESPONSE" = "200" ]; then
          echo "Attempting to test project creation permissions..."
          # This will fail but should give us info about permissions
          curl -s -o /dev/null -w "%{http_code}" -X PUT \
            -H "Content-Type: application/vnd.docker.distribution.manifest.v2+json" \
            -u "${{ secrets.CERIT_REGISTRY_USERNAME }}:${{ secrets.CERIT_REGISTRY_PASSWORD }}" \
            -d '{"schemaVersion":2,"config":{"mediaType":"application/vnd.docker.container.image.v1+json","digest":"sha256:0000000000000000000000000000000000000000000000000000000000000000","size":2},"layers":[]}' \
            "https://${{ env.REGISTRY }}/v2/molstar/test-repo/manifests/latest" || echo "Test completed"
        fi
        
        echo "=== Summary ==="
        if [ "$ROOT_RESPONSE" = "200" ]; then
          echo "✓ Authentication is working"
          echo "✓ Registry is accessible"
          echo "Repository '${{ env.IMAGE_NAME }}' will be created automatically on first push."
        else
          echo "✗ Authentication failed - check credentials"
          echo "Please verify:"
          echo "1. CERIT_REGISTRY_USERNAME is correct"
          echo "2. CERIT_REGISTRY_PASSWORD is correct"
          echo "3. User has access to cerit.io registry"
          exit 1
        fi

    - name: Build and push Docker image
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v5
      with:
        context: ./api
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        platforms: linux/amd64
        # Temporarily disable cache to isolate the issue
        # cache-from: type=gha
        # cache-to: type=gha,mode=max

  deploy-dev:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        echo "${{ secrets.K8S_CONTEXT }}" | base64 -d > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml

    - name: Deploy to development
      run: |
        export KUBECONFIG=kubeconfig.yaml
        
        # Set image tag based on branch
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          IMAGE_TAG="latest"
        else
          IMAGE_TAG="${{ github.ref_name }}"
        fi
        
        # Check if development deployment exists
        if kubectl get deployment/mol-view-stories-dev-api -n mol-view-stories-ns >/dev/null 2>&1; then
          echo "Development deployment exists, updating image..."
          # Update deployment with new image
          kubectl set image deployment/mol-view-stories-dev-api \
            mol-view-stories-dev-api-container=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG} \
            -n mol-view-stories-ns
          
          # Restart deployment to ensure new image is pulled
          kubectl rollout restart deployment/mol-view-stories-dev-api -n mol-view-stories-ns
          
          # Wait for rollout to complete
          kubectl rollout status deployment/mol-view-stories-dev-api -n mol-view-stories-ns --timeout=300s
        else
          echo "Development deployment does not exist, creating from production deployment..."
          # Get the production deployment and create a development version
          kubectl get deployment/mol-view-stories-api -n mol-view-stories-ns -o yaml | \
            sed 's/name: mol-view-stories-api/name: mol-view-stories-dev-api/g' | \
            sed 's/mol-view-stories-api-container/mol-view-stories-dev-api-container/g' | \
            sed 's/replicas: [0-9]*/replicas: 1/g' | \
            kubectl apply -f -
          
          # Update the image to the new tag
          kubectl set image deployment/mol-view-stories-dev-api \
            mol-view-stories-dev-api-container=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG} \
            -n mol-view-stories-ns
          
          # Wait for rollout to complete
          kubectl rollout status deployment/mol-view-stories-dev-api -n mol-view-stories-ns --timeout=300s
        fi

    - name: Verify deployment
      run: |
        export KUBECONFIG=kubeconfig.yaml
        kubectl get pods -n mol-view-stories-ns -l app=mol-view-stories-dev-api 