name: PR Validation

on:
  pull_request:
    branches: ["main"]
    paths:
      - "api/**"
      - ".github/workflows/pr-check.yml"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd api
          pip install -r requirements.txt
          pip install flake8 black isort bandit safety pytest

      - name: Run linting (flake8)
        run: |
          cd api
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run code formatting check (black)
        run: |
          cd api
          black --check --diff .

      - name: Run import sorting check (isort)
        run: |
          cd api
          isort --check-only --diff .

      - name: Run security scanning (bandit)
        run: |
          cd api
          bandit -r . -f json -o bandit-report.json || true
          bandit -r . -f txt -o bandit-report.txt || true

      - name: Run dependency security check (safety)
        run: |
          cd api
          safety check --json --output api/safety-report.json || true
          safety check --full-report || true

      - name: Run tests
        run: |
          cd api
          python -m pytest tests/ -v --cov=. --cov-report=xml --cov-report=html

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./api/coverage.xml
          flags: api
          name: api-coverage

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (without pushing)
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: false
          tags: test-image:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify Docker image
        run: |
          docker images test-image:latest
          docker run --rm test-image:latest python --version 