name: Production Deployment

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        default: 'latest'
        type: string
      confirm_deployment:
        description: 'Confirm production deployment'
        required: true
        type: boolean

env:
  REGISTRY: hub.cerit.io
  IMAGE_NAME: molstar/mol-view-stories

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    if: inputs.confirm_deployment == true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          echo "${{ secrets.K8S_CONTEXT }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Update deployment with image tag
        run: |
          export KUBECONFIG=kubeconfig
          kubectl set image deployment/mol-view-stories-api mol-view-stories-api=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag }} -n mol-view-stories-ns

      - name: Set MinIO environment variables for production
        run: |
          export KUBECONFIG=kubeconfig
          kubectl set env deployment/mol-view-stories-api \
            -n mol-view-stories-ns \
            -c mol-view-stories-api \
            MINIO_ENDPOINT="${{ secrets.MINIO_PROD_URL }}" \
            MINIO_ACCESS_KEY="${{ secrets.MINIO_PROD_USERNAME }}" \
            MINIO_SECRET_KEY="${{ secrets.MINIO_PROD_PASSWORD }}" \
            MINIO_BUCKET="root"

      - name: Deploy to production
        run: |
          export KUBECONFIG=kubeconfig
          kubectl apply -f api/deploy.yaml
          kubectl rollout status deployment/mol-view-stories-api -n mol-view-stories-ns

      - name: Health check
        run: |
          export KUBECONFIG=kubeconfig
          kubectl wait --for=condition=ready pod -l app=mol-view-stories-api -n mol-view-stories-ns --timeout=300s

      - name: Verify deployment
        run: |
          export KUBECONFIG=kubeconfig
          kubectl get pods -n mol-view-stories-ns -l app=mol-view-stories-api
          kubectl get services -n mol-view-stories-ns -l app=mol-view-stories-api

      - name: Deployment summary
        run: |
          echo "## Production Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Image Tag**: ${{ inputs.image_tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Registry**: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Deployment Time**: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ✅ Successfully deployed" >> $GITHUB_STEP_SUMMARY 